// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlkAD2OMy0zuzkJAYIeDrP-SqdXmaz8fg',
    appId: '1:222233995854:web:e8389297ffe883c595311f',
    messagingSenderId: '222233995854',
    projectId: 'finstagram-d8ebf',
    authDomain: 'finstagram-d8ebf.firebaseapp.com',
    storageBucket: 'finstagram-d8ebf.appspot.com',
    measurementId: 'G-H38594MSLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuZnycyUDIRIXiSmerXNxUtyvBQxRQyT0',
    appId: '1:222233995854:android:c11eaa3c0b5980a595311f',
    messagingSenderId: '222233995854',
    projectId: 'finstagram-d8ebf',
    storageBucket: 'finstagram-d8ebf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgzmbILkagPnVkztITLx386hZb-qWylrg',
    appId: '1:222233995854:ios:71177dcdf6d213d995311f',
    messagingSenderId: '222233995854',
    projectId: 'finstagram-d8ebf',
    storageBucket: 'finstagram-d8ebf.appspot.com',
    iosBundleId: 'com.example.instaclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgzmbILkagPnVkztITLx386hZb-qWylrg',
    appId: '1:222233995854:ios:71177dcdf6d213d995311f',
    messagingSenderId: '222233995854',
    projectId: 'finstagram-d8ebf',
    storageBucket: 'finstagram-d8ebf.appspot.com',
    iosBundleId: 'com.example.instaclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlkAD2OMy0zuzkJAYIeDrP-SqdXmaz8fg',
    appId: '1:222233995854:web:d34f5475429b0e8895311f',
    messagingSenderId: '222233995854',
    projectId: 'finstagram-d8ebf',
    authDomain: 'finstagram-d8ebf.firebaseapp.com',
    storageBucket: 'finstagram-d8ebf.appspot.com',
    measurementId: 'G-S6V525NWXT',
  );

}